---
# tasks file for Apache
 - include: CentOS.yml
   when: ansible_distribution == "CentOS"

 - include: Ubuntu.yml
   when: ansible_distribution == "Ubuntu"

 - include: copy_centos.yml
   when: ansible_distribution == "CentOS"

 - include: copy_ubuntu.yml
   when: ansible_distribution == "Ubuntu"

